Adds web crawler
mateuscelio/watchlist pull request #1
Opened 2022-04-05 13:37 UTC by mateuscelio

* Adds service to get the current quote given an asset symbol
* Creates scrapper for Infomoney and Status invest

2022-04-05 20:42 UTC, lukzgois requested changes
Deixei alguns comentários, mas o PR está muito bem organizado e simples de entender. Parabéns!

2022-04-05 20:42 UTC, lukzgois commented on app/services/quotes/current_asset_quote_getter.rb
> +      InfoMoneyScrapper.quote_for(@asset_symbol)
O que acontece no caso do scrapper da `InfoMoney` também falhar?

2022-04-05 20:42 UTC, lukzgois commented on app/services/quotes/scrapper_base.rb
> +      res = HTTParty.get(quote_url(asset_symbol))
Nesse caso esta sendo disparado o crawler para o `asset_symbol`, independente de ele ser suportado ou nao. Acho que seria interessante adicionar um `guard` para verificar isso antes de disparar a requisição.

2022-04-06 20:27 UTC, mateuscelio commented on app/services/quotes/scrapper_base.rb
> +      res = HTTParty.get(quote_url(asset_symbol))
https://github.com/mateuscelio/watchlist/pull/1/commits/d9294628b849dc73a1dfba22958424b72cdc35c1

2022-04-07 18:27 UTC, lukzgois approved these changes

2022-04-08 14:28 UTC, merged